// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
	"gorm.io/gorm"
)

type Products struct {
	ID          int       `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	Name        string    `gorm:"column:name;NOT NULL"`
	Description string    `gorm:"column:description"`
	Price       string    `gorm:"column:price;NOT NULL"`
	Stock       int       `gorm:"column:stock;NOT NULL"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func MigrateModels(db *gorm.DB) {
    db.AutoMigrate(&Products{})
}
